# Generated by Django 4.1.5 on 2023-01-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_clients', models.TextField()),
                ('coll_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sends.message')),
                ('coll_newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sends.newsletter')),
            ],
        ),
    ]
