# Generated by Django 4.1.5 on 2023-02-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='letter_mails',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
    ]
