# Generated by Django 4.1.5 on 2023-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0002_newsletter_letter_mails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='letter_clients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='letter_mails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
